# Building stage
FROM node:14.2-slim as builder
WORKDIR /usr/src/app

COPY package*.json ./
COPY preact.config.js ./
COPY src src/
COPY server server/
COPY .babelrc ./
COPY .env.staging ./
RUN npm ci
RUN npm run build:stag_prd
RUN npm run build:server
RUN ls -al 

# Starting stage
FROM node:14.2-slim
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/node_modules node_modules/
COPY --from=builder /usr/src/app/build build/
COPY --from=builder /usr/src/app/dist dist/
COPY --from=builder /usr/src/app/package.json .
EXPOSE 8000 8000
CMD [ "npm", "run", "start:server-stag"]