name: Deploy-to-DO-production

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Web Preact - Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          URL_API: ${{ secrets.ENV_URL_API }}
          SERVER_PORT: ${{ secrets.ENV_SERVER_PORT }}
          SSR: ${{ secrets.ENV_SSR }}
        with:
          name: kuclap/kuclap/kuclap-web
          registry: docker.pkg.github.com
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./docker/Web.Dockerfile
          tags: latest
          buildargs: URL_API,SERVER_PORT,SSR
      - name: Nginx - Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: kuclap/kuclap/kuclap-nginx
          registry: docker.pkg.github.com
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./docker/Nginx.Dockerfile
          tags: latest
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.GIT_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          port: ${{ secrets.DO_PORT }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            docker stop $(docker ps -a -q)
            docker container prune -f 
            docker image prune -f
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/kuclap/kuclap/kuclap-web:latest
            docker pull docker.pkg.github.com/kuclap/kuclap/kuclap-nginx:latest
            docker run --restart=always --network=kuclap -dit --name kuclap-web -p 8000:8000 docker.pkg.github.com/kuclap/kuclap/kuclap-web:latest 
            docker run --network=kuclap -dit --name kuclap-nginx -p 80:80 docker.pkg.github.com/kuclap/kuclap/kuclap-nginx:latest
