name: Deploy-to-DO-production

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Web Preact - Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          URL_API: ${{ secrets.ENV_URL_API }}
          SERVER_PORT: ${{ secrets.ENV_SERVER_PORT }}
          SSR: ${{ secrets.ENV_SSR }}
        with:
          name: kuclap/kuclap/kuclap-web
          registry: docker.pkg.github.com
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./docker/Web.Dockerfile
          tags: "1.0.0, latest"
          buildargs: URL_API,SERVER_PORT,SSR
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.DO_GANDALF_HOST }}
          username: ${{ secrets.DO_GANDALF_USERNAME }}
          password: ${{ secrets.DO_GANDALF_PASSWORD }}
          port: ${{ secrets.DO_GANDALF_PORT }}
          envs: GIT_USERNAME, GITHUB_TOKEN
          script: |
            docker stop kuclap-web
            docker container prune -f 
            docker image prune -f
            docker login docker.pkg.github.com -u $GIT_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/kuclap/kuclap/kuclap-web:latest
            docker run --name kuclap-web --network=kuclap --restart=always  -dit -p 8000:8000 docker.pkg.github.com/kuclap/kuclap/kuclap-web:latest
